import React, { useEffect, useState } from "react";
import {
  createProjectSpace,
  fetchProjectSpaces,
  fetchRootStatus,
  formatApiError,
  rootLogin,
  rootLogout,
} from "../lib/registry.js";
import type { ProjectSpaceSummary } from "../lib/types.js";
import { relativeTime } from "../styles/ui.js";
import "./RootPage.css";

export function RootPage() {
  const [authenticated, setAuthenticated] = useState<boolean | null>(null);

  useEffect(() => {
    fetchRootStatus()
      .then((status) => setAuthenticated(status.authenticated))
      .catch(() => setAuthenticated(false));
  }, []);

  if (authenticated === null) return null;
  return authenticated ? <RootConsole onSignedOut={() => setAuthenticated(false)} /> : <RootLogin onSignedIn={() => setAuthenticated(true)} />;
}

function RootLogin({ onSignedIn }: { onSignedIn: () => void }) {
  const [key, setKey] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    if (!key.trim()) return;
    setBusy(true);
    setError(null);
    try {
      await rootLogin(key.trim());
      onSignedIn();
    } catch (err) {
      setError(formatApiError(err));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="root-login">
      <form className="root-login__card k-section" onSubmit={(event) => { void submit(event); }}>
        <div className="k-section__header">Root access</div>
        <div className="k-section__body root-login__body">
          <p className="root-login__hint">
            Enter the 32-character root key generated by <code>konductor setup</code>.
          </p>
          <div className="k-field">
            <label className="k-label" htmlFor="root-key">Root key</label>
            <input
              id="root-key"
              className="k-input k-mono"
              type="password"
              autoComplete="off"
              autoFocus
              value={key}
              onChange={(event) => setKey(event.target.value)}
            />
          </div>
          {error ? <p className="k-error">{error}</p> : null}
          <div className="k-actions">
            <button className="k-btn k-btn--primary" disabled={busy || !key.trim()}>
              {busy ? "Checking…" : "Continue"}
            </button>
          </div>
        </div>
      </form>
    </div>
  );
}

function RootConsole({ onSignedOut }: { onSignedOut: () => void }) {
  const [spaces, setSpaces] = useState<ProjectSpaceSummary[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);

  function reload() {
    fetchProjectSpaces()
      .then((res) => setSpaces(res.spaces))
      .catch((err) => setError(formatApiError(err)));
  }

  useEffect(reload, []);

  async function signOut() {
    await rootLogout().catch(() => {});
    onSignedOut();
  }

  return (
    <div className="root-console">
      <div className="k-toolbar">
        <span className="k-toolbar__title">Project spaces</span>
        <span className="k-faint k-num">{spaces ? spaces.length : ""}</span>
        <div className="root-console__spacer" />
        <button className="k-btn k-btn--primary k-btn--sm" onClick={() => setCreating(true)}>New space</button>
        <button className="k-btn k-btn--ghost k-btn--sm" onClick={() => { void signOut(); }}>Sign out</button>
      </div>

      <div className="k-page">
        {error ? <p className="k-error">{error}</p> : null}
        {!spaces ? (
          <p className="k-loading">Loading…</p>
        ) : spaces.length === 0 ? (
          <div className="root-console__empty">
            <p>No project spaces yet.</p>
            <button className="k-btn k-btn--primary" onClick={() => setCreating(true)}>Create the first space</button>
          </div>
        ) : (
          <div className="k-table-scroll">
            <table className="k-table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th className="k-num">Admins</th>
                  <th>Created</th>
                </tr>
              </thead>
              <tbody>
                {spaces.map((space) => (
                  <tr key={space.id}>
                    <td className="root-console__name">{space.name}</td>
                    <td className="k-num">{space.admin_count}</td>
                    <td className="k-muted">{relativeTime(space.created_at)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {creating ? (
        <NewSpaceDialog
          onClose={() => setCreating(false)}
          onCreated={() => { setCreating(false); reload(); }}
        />
      ) : null}
    </div>
  );
}

function NewSpaceDialog({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const [name, setName] = useState("");
  const [adminName, setAdminName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    setBusy(true);
    setError(null);
    try {
      await createProjectSpace({
        name: name.trim(),
        admin: { display_name: adminName.trim(), email: email.trim(), password },
      });
      onCreated();
    } catch (err) {
      setError(formatApiError(err));
    } finally {
      setBusy(false);
    }
  }

  const valid = name.trim() && adminName.trim() && email.trim() && password.length >= 12;

  return (
    <div className="k-backdrop" onClick={onClose}>
      <section className="k-dialog root-console__dialog" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}>
        <header className="k-dialog__header">
          New project space
          <button type="button" className="k-dialog__close" onClick={onClose} aria-label="Close">×</button>
        </header>
        <form className="k-dialog__body root-console__form" onSubmit={(event) => { void submit(event); }}>
          <div className="k-field">
            <label className="k-label" htmlFor="space-name">Space name</label>
            <input id="space-name" className="k-input" autoFocus value={name} onChange={(event) => setName(event.target.value)} />
          </div>
          <div className="k-field">
            <label className="k-label" htmlFor="admin-name">Admin name</label>
            <input id="admin-name" className="k-input" value={adminName} onChange={(event) => setAdminName(event.target.value)} />
          </div>
          <div className="k-field">
            <label className="k-label" htmlFor="admin-email">Admin email</label>
            <input id="admin-email" className="k-input" type="email" value={email} onChange={(event) => setEmail(event.target.value)} />
          </div>
          <div className="k-field">
            <label className="k-label" htmlFor="admin-password">Admin password</label>
            <input id="admin-password" className="k-input" type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} />
            <span className="k-hint">At least 12 characters.</span>
          </div>
          {error ? <p className="k-error">{error}</p> : null}
          <div className="k-actions">
            <button type="button" className="k-btn k-btn--ghost" onClick={onClose}>Cancel</button>
            <button className="k-btn k-btn--primary" disabled={busy || !valid}>{busy ? "Creating…" : "Create space"}</button>
          </div>
        </form>
      </section>
    </div>
  );
}
